// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZun2dwhfW3XyxgAeiaBMbCRHIdUgGKV0',
    appId: '1:634172370359:web:4fed6dea88ea22ff2f4c32',
    messagingSenderId: '634172370359',
    projectId: 'codepie-3d428',
    authDomain: 'codepie-3d428.firebaseapp.com',
    storageBucket: 'codepie-3d428.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lKPd2Yh8Y3A4X6tHpQzrx7EC-dddf88',
    appId: '1:634172370359:android:de4cd4559bc2f7fc2f4c32',
    messagingSenderId: '634172370359',
    projectId: 'codepie-3d428',
    storageBucket: 'codepie-3d428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7t_EsvOjOKimf-k4WhBlaDT9rhTglCXU',
    appId: '1:634172370359:ios:ca32703cd62bf6c02f4c32',
    messagingSenderId: '634172370359',
    projectId: 'codepie-3d428',
    storageBucket: 'codepie-3d428.appspot.com',
    iosBundleId: 'com.example.codepie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7t_EsvOjOKimf-k4WhBlaDT9rhTglCXU',
    appId: '1:634172370359:ios:ca32703cd62bf6c02f4c32',
    messagingSenderId: '634172370359',
    projectId: 'codepie-3d428',
    storageBucket: 'codepie-3d428.appspot.com',
    iosBundleId: 'com.example.codepie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZun2dwhfW3XyxgAeiaBMbCRHIdUgGKV0',
    appId: '1:634172370359:web:8f95d4210c0b064b2f4c32',
    messagingSenderId: '634172370359',
    projectId: 'codepie-3d428',
    authDomain: 'codepie-3d428.firebaseapp.com',
    storageBucket: 'codepie-3d428.appspot.com',
  );
}
